### ISSUE TITLE
Ret rapporten

### ISSUE THREAD

**Issue by Sarmisuper** [KarmaKamikaze/GeneticDFA#34]

**Comment by KarmaKamikaze** [comment]
- [x] Summary
- [x] Abstract
- [x] Introduction
- [x] Part I
- [x] Problem Analysis (Trains)
- [x] Reverse Engineering RF-Signals
- [x] Part II
- [x] Problem Analysis
- [x] Design
- [x] Implementation
- [x] Findings
- [x] Discussion
- [x] Conclusion
- [x] Future Work
